// Generated by CoffeeScript 1.6.2
/*
  Class: Edge

  Describes an edge going between two nodes. Both
  nodes at the ends of the edge will store a reference
  to an instantiated Edge. Since all our edges are
  unidirectional and hierarchical in nature, we can think
  of these edges as establishing parent-child relationships
  between two given nodes.
*/


(function() {
  var Edge;

  Edge = (function() {
    /*
      Describes an edge going from n1 to n2 of 
      some type.
    
      The four types are:
        1:   one  -> one
        2:   one  -> many
        3:   many -> one
        4:   many -> many
    */
    function Edge(n1, n2, type) {
      this._n1 = n1;
      this._n2 = n2;
      this._type = type;
    }

    Edge.prototype.__defineGetter__('parent', function() {
      return this._n1;
    });

    Edge.prototype.__defineGetter__('child', function() {
      return this._n2;
    });

    return Edge;

  })();

  module.exports = Edge;

}).call(this);
