// Generated by CoffeeScript 1.4.0

/*
  Class: GraphBuilder

  Basic builder interface to construct a graph of resources
  defined config file.
*/


(function() {
  var GraphDirector,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  GraphDirector = (function() {
    /*
        Constructor
    
        Takes a Graph and Builder.
    */

    function GraphDirector(graph, builder) {
      this.build = __bind(this.build, this);
      this._graph = graph;
      this._builder = builder;
      if (this._builder.setGraph != null) {
        this._builder.setGraph(this._graph);
      }
    }

    GraphDirector.prototype.build = function(callback) {
      var _this = this;
      return this._builder.preBuild(function(err) {
        return _this._builder.build(function(err) {
          return _this._builder.postBuild(function(err) {
            return callback(null);
          });
        });
      });
    };

    return GraphDirector;

  })();

  module.exports = GraphDirector;

}).call(this);
