// Generated by CoffeeScript 1.4.0

/*
  Class: Graph

  Class instance exported to client applications.

  Encapsulates the graph data structure among resources
  as well as direct access to the database drivers.
*/


(function() {
  var Graph;

  Graph = (function() {

    function Graph() {
      this._nodes = [];
      this._drivers = {};
    }

    Graph.prototype.setDrivers = function(drivers) {
      return this._drivers = drivers;
    };

    Graph.prototype.setNodeManager = function(nodeManager) {
      return this._nodeManager = nodeManager;
    };

    Graph.prototype.__defineGetter__('drivers', function() {
      return this._drivers;
    });

    Graph.prototype.__defineGetter__('nodeManager', function() {
      return this._nodeManager;
    });

    return Graph;

  })();

  module.exports = Graph;

}).call(this);
