// Generated by CoffeeScript 1.6.2
/*
  Class: NodeManager

  Node Manager provides an interface for the application to get information about
  the resource graph.  This NodeManager should get
*/


(function() {
  var NodeManager;

  NodeManager = (function() {
    function NodeManager(nodes) {
      this.__nodes = nodes;
    }

    NodeManager.prototype.getParents = function(node) {
      return node.parents;
    };

    NodeManager.prototype.getChildren = function(node) {
      return node.children;
    };

    NodeManager.prototype.find = function(nodeName) {
      var _n;

      _n = _.filter(this.__nodes, function(n) {
        return _.contains([n.name, n.alternateName], nodeName);
      });
      return _n[0];
    };

    NodeManager.prototype.__defineGetter__('nodes', function() {
      return this.__nodes;
    });

    return NodeManager;

  })();

  module.exports = NodeManager;

}).call(this);
