// Generated by CoffeeScript 1.4.0
(function() {
  var NodeManager;

  NodeManager = (function() {

    function NodeManager() {}

    /*
        Method: addChild
    
        Adds child to a given parent
    */


    NodeManager.prototype.addChild = function(parent, child) {
      return console.log("Adding parent - child in NodeManager " + parent + " " + child);
    };

    /*
        Method: orphan
    
        Adds an orphan to the orphaned Node set
    */


    NodeManager.prototype.addOrphan = function(orphan) {
      return console.log("Adding orphan in NodeManager " + orphan);
    };

    NodeManager.prototype.__defineGetter__('nodes', function() {
      return this._nodes;
    });

    NodeManager.prototype.getNodes = function() {};

    return NodeManager;

  })();

  module.exports = NodeManager;

}).call(this);
