// Generated by CoffeeScript 1.4.0

/*
  Class: NodeManager

  Node Managaer provides an interface for the application to get information about
  the resource graph.  This NodeManager should get
*/


(function() {
  var NodeManager;

  NodeManager = (function() {

    function NodeManager() {}

    NodeManager.prototype.someOperation = function() {};

    NodeManager.prototype.someOtherOperation = function() {};

    /*
        Method: addChild
    
        Adds child to a given parent
    */


    return NodeManager;

  })();

  module.exports = NodeManager;

}).call(this);
